[project]
name = "project-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "khanv02", email = "189113800+khanv02@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.8.0",
    "numpy>=1.26.0",
    "opencv-python>=4.8.0",
    "pillow>=10.0.0",
    "pyside6>=6.6.0",
    "scikit-image>=0.22.0",
]

[project.scripts]
project-1 = "project_1:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
